manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/PippinW
  projects:
    - name: PippinW
      remote: zmk
      revision: main
      import: app/west.yml
  self:
    path: config
